"""Sequential in-process worker for resumable whole-document analysis tasks."""

from datetime import UTC, datetime
from typing import Any, Protocol

from comic_agent.config import Settings
from comic_agent.providers.llm import LLMProvider
from comic_agent.repositories.agent_run_repository import AgentRunRepository
from comic_agent.repositories.narrative_analysis_recovery_repository import (
    NarrativeAnalysisRecoveryRepository,
)
from comic_agent.repositories.narrative_analysis_repository import NarrativeAnalysisRepository
from comic_agent.repositories.source_repository import SourceRepository
from comic_agent.schemas.workflow import (
    AgentRunStatus,
    NarrativeAnalysisProposalSourceV1,
    NarrativeAnalysisRunStatus,
    NarrativeAnalysisRunV1,
    NarrativeAnalysisWindowStatus,
    NarrativeAnalysisWindowV1,
)
from comic_agent.services.narrative_analysis_aggregation import aggregate_narrative_analysis
from comic_agent.services.narrative_analysis_proposal_sources import proposal_sources_for_window
from comic_agent.services.narrative_analysis_recovery_coordinator import (
    NarrativeAnalysisRecoveryCoordinator,
    default_recovery_policy,
)
from comic_agent.services.narrative_analysis_review_coordinator import (
    NarrativeAnalysisReviewCoordinator,
)
from comic_agent.services.narrative_analyst_summary import (
    FAILURE_RECOMMENDED_ACTIONS,
    add_provider_diagnostics,
    classify_exception,
    recommended_action_for_failure,
    sanitize_error_message,
    sanitize_provider_diagnostics,
    set_failure,
)
from comic_agent.workflows.narrative_analyst_workflow import NarrativeAnalystWorkflow

MAX_AUTOMATIC_WINDOW_ATTEMPTS = 2
LENGTH_RETRY_MAX_CHARS_PER_CHUNK = 800
RETRYABLE_FAILURE_CATEGORIES = {
    "PROVIDER_LENGTH_BEFORE_FINAL_CONTENT",
    "SCHEMA_VALIDATION_FAILED",
}


class _AgentRunStore(Protocol):
    def save_agent_run(self, agent_run: object) -> object:
        """Persist an AgentRun generated by the existing workflow."""


class NarrativeAnalysisWorker:
    """Run pending windows one at a time and leave completed windows untouched on resume."""

    def __init__(
        self,
        *,
        settings: Settings,
        source_repository: SourceRepository,
        agent_run_repository: AgentRunRepository | _AgentRunStore,
        analysis_repository: NarrativeAnalysisRepository,
        recovery_repository: NarrativeAnalysisRecoveryRepository | None = None,
        provider: LLMProvider | None = None,
    ) -> None:
        self._settings = settings
        self._source_repository = source_repository
        self._agent_run_repository = agent_run_repository
        self._analysis_repository = analysis_repository
        self._recovery_repository = recovery_repository
        self._provider = provider

    def run_pending(
        self,
        analysis_run_id: str,
        *,
        real_llm_requested: bool | None = None,
    ) -> NarrativeAnalysisRunV1:
        """Execute only pending or failed windows in deterministic sequential order."""

        run = self._analysis_repository.get_run(analysis_run_id)
        if run is None:
            raise ValueError("NarrativeAnalysisRun not found")
        requested_real_llm = (
            run.real_llm_requested if real_llm_requested is None else real_llm_requested
        )
        run = run.model_copy(
            update={"status": NarrativeAnalysisRunStatus.RUNNING, "updated_at": datetime.now(UTC)}
        )
        self._analysis_repository.save_run(run)
        workflow = NarrativeAnalystWorkflow(
            settings=self._settings,
            source_repository=self._source_repository,
            agent_run_repository=self._agent_run_repository,  # type: ignore[arg-type]
            provider=self._provider,
        )
        pending_windows = [
            window
            for window in self._analysis_repository.list_windows(analysis_run_id)
            if window.status
            in (NarrativeAnalysisWindowStatus.PENDING, NarrativeAnalysisWindowStatus.FAILED)
        ]
        pending_windows.sort(key=lambda window: (run.modes.index(window.mode), window.window_index))
        for window in pending_windows:
            self._run_window(workflow, run, window, requested_real_llm)
        return self._finalize_run(analysis_run_id, workflow, requested_real_llm)

    def _run_window(
        self,
        workflow: NarrativeAnalystWorkflow,
        run: NarrativeAnalysisRunV1,
        window: NarrativeAnalysisWindowV1,
        real_llm_requested: bool,
    ) -> None:
        current = window
        while True:
            running = current.model_copy(
                update={
                    "status": NarrativeAnalysisWindowStatus.RUNNING,
                    "error_message": None,
                    "failure_category": None,
                    "recommended_action": None,
                    "attempt_count": current.attempt_count + 1,
                }
            )
            self._analysis_repository.save_window(running)
            completed = self._run_window_attempt(
                workflow,
                run,
                running,
                real_llm_requested,
            )
            self._analysis_repository.save_window(completed)
            if self._should_split(completed):
                self._split_length_failed_window(workflow, run, completed, real_llm_requested)
                return
            if not self._should_retry(completed):
                return
            current = completed.model_copy(
                update={
                    "previous_failure_category": completed.failure_category,
                    "effective_max_chars_per_chunk": self._retry_max_chars_per_chunk(completed),
                }
            )

    def _run_window_attempt(
        self,
        workflow: NarrativeAnalystWorkflow,
        run: NarrativeAnalysisRunV1,
        running: NarrativeAnalysisWindowV1,
        real_llm_requested: bool,
    ) -> NarrativeAnalysisWindowV1:
        """Run one persisted attempt without weakening provider or evidence validation."""

        try:
            result = workflow.run(
                project_id=run.project_id,
                mode=running.mode,
                chunk_ids=running.chunk_ids,
                chunk_limit=len(running.chunk_ids),
                max_chars_per_chunk=running.effective_max_chars_per_chunk,
                output_recovery=self._output_recovery(running),
                output_recovery_rule_codes=self._output_recovery_rule_codes(running),
                real_llm_requested=real_llm_requested,
            )
            agent_run_id = result.agent_run.agent_run_id if result.agent_run is not None else None
            failed = (
                result.agent_run is not None and result.agent_run.status == AgentRunStatus.FAILED
            )
            failure_details = self._failure_details_from_summary(result.summary) if failed else {}
            return running.model_copy(
                update={
                    "status": (
                        NarrativeAnalysisWindowStatus.FAILED
                        if failed
                        else NarrativeAnalysisWindowStatus.SUCCEEDED
                    ),
                    "agent_run_id": agent_run_id,
                    **failure_details,
                }
            )
        except Exception as exc:
            failure_summary: dict[str, Any] = {}
            add_provider_diagnostics(failure_summary, exc)
            set_failure(failure_summary, classify_exception(exc))
            selected_chunks = [
                chunk
                for chunk_id in running.chunk_ids
                if (chunk := self._source_repository.get_chunk(chunk_id)) is not None
            ]
            return running.model_copy(
                update={
                    "status": NarrativeAnalysisWindowStatus.FAILED,
                    "agent_run_id": None,
                    "error_message": sanitize_error_message(
                        str(exc),
                        settings=self._settings,
                        selected_chunks=selected_chunks,
                    ),
                    "failure_category": failure_summary["failure_category"],
                    "recommended_action": failure_summary["recommended_action"],
                    "provider_error_diagnostics": sanitize_provider_diagnostics(
                        failure_summary.get("provider_error_diagnostics")
                    ),
                }
            )

    def _should_retry(self, window: NarrativeAnalysisWindowV1) -> bool:
        """Allow one bounded automatic retry only for recoverable provider failures."""

        return (
            window.status == NarrativeAnalysisWindowStatus.FAILED
            and window.attempt_count < MAX_AUTOMATIC_WINDOW_ATTEMPTS
            and window.failure_category in RETRYABLE_FAILURE_CATEGORIES
        )

    def _should_split(self, window: NarrativeAnalysisWindowV1) -> bool:
        """Split only a multi-SourceChunk length failure at auditable boundaries."""

        return (
            window.status == NarrativeAnalysisWindowStatus.FAILED
            and window.failure_category == "PROVIDER_LENGTH_BEFORE_FINAL_CONTENT"
            and len(window.chunk_ids) > 1
        )

    def _split_length_failed_window(
        self,
        workflow: NarrativeAnalystWorkflow,
        run: NarrativeAnalysisRunV1,
        failed_window: NarrativeAnalysisWindowV1,
        real_llm_requested: bool,
    ) -> None:
        """Create and execute one deterministic child window per source chunk."""

        owned_ids = [
            chunk_id
            for chunk_id in failed_window.chunk_ids
            if chunk_id in set(failed_window.owned_chunk_ids)
        ]
        chunks = [
            chunk
            for chunk_id in owned_ids
            if (chunk := self._source_repository.get_chunk(chunk_id)) is not None
        ]
        if len(chunks) != len(owned_ids):
            return
        child_windows = [
            NarrativeAnalysisWindowV1(
                analysis_window_id=f"{failed_window.analysis_window_id}:split:{index}",
                analysis_run_id=failed_window.analysis_run_id,
                mode=failed_window.mode,
                window_index=(failed_window.window_index + 1) * 100_000 + index,
                chunk_ids=[chunk.chunk_id],
                owned_chunk_ids=[chunk.chunk_id],
                status=NarrativeAnalysisWindowStatus.PENDING,
                effective_max_chars_per_chunk=max(
                    failed_window.effective_max_chars_per_chunk,
                    len(chunk.text),
                ),
                previous_failure_category=failed_window.failure_category,
                parent_window_id=failed_window.analysis_window_id,
                split_reason=failed_window.failure_category,
            )
            for index, chunk in enumerate(chunks)
        ]
        create_windows = getattr(self._analysis_repository, "create_windows", None)
        if not callable(create_windows):
            return
        create_windows(child_windows)
        split_window = failed_window.model_copy(
            update={
                "status": NarrativeAnalysisWindowStatus.SPLIT,
                "split_reason": failed_window.failure_category,
            }
        )
        self._analysis_repository.save_window(split_window)
        updated_window_ids = list(run.window_ids)
        for child in child_windows:
            if child.analysis_window_id not in updated_window_ids:
                updated_window_ids.append(child.analysis_window_id)
        self._analysis_repository.save_run(
            run.model_copy(
                update={
                    "window_ids": updated_window_ids,
                    "updated_at": datetime.now(UTC),
                }
            )
        )
        for child in child_windows:
            self._run_window(workflow, run, child, real_llm_requested)

    def _retry_max_chars_per_chunk(self, window: NarrativeAnalysisWindowV1) -> int:
        """Reduce only a length-truncated window; schema retries retain the same context."""

        if window.failure_category == "PROVIDER_LENGTH_BEFORE_FINAL_CONTENT":
            return min(LENGTH_RETRY_MAX_CHARS_PER_CHUNK, window.effective_max_chars_per_chunk)
        return window.effective_max_chars_per_chunk

    def _output_recovery(self, window: NarrativeAnalysisWindowV1) -> str | None:
        """Pass a fixed, content-free correction marker only on the retry attempt."""

        if window.previous_failure_category == "SCHEMA_VALIDATION_FAILED":
            if window.mode == "state_change_extraction":
                return "state_change_schema_recovery"
            return "schema_validation"
        if window.previous_failure_category == "PROVIDER_LENGTH_BEFORE_FINAL_CONTENT":
            if window.effective_max_chars_per_chunk > LENGTH_RETRY_MAX_CHARS_PER_CHUNK:
                return "length_split"
            return "length_reduction"
        return None

    @staticmethod
    def _output_recovery_rule_codes(window: NarrativeAnalysisWindowV1) -> list[str] | None:
        diagnostics = window.provider_error_diagnostics
        if not isinstance(diagnostics, dict):
            return None
        rule_codes = diagnostics.get("schema_error_rule_codes")
        if not isinstance(rule_codes, list):
            return None
        safe_codes = sorted({code for code in rule_codes if isinstance(code, str)})
        return safe_codes or None

    def _failure_details_from_summary(self, summary: dict[str, Any]) -> dict[str, object]:
        """Map an already-sanitized failed workflow summary to a window audit record."""

        category = summary.get("failure_category")
        if not isinstance(category, str) or category not in FAILURE_RECOMMENDED_ACTIONS:
            category = "UNKNOWN_ERROR"
        error_message = summary.get("error_message")
        diagnostics = sanitize_provider_diagnostics(summary.get("provider_error_diagnostics"))
        return {
            "error_message": error_message if isinstance(error_message, str) else None,
            "failure_category": category,
            "recommended_action": recommended_action_for_failure(category, diagnostics),
            "provider_error_diagnostics": diagnostics,
        }

    def _finalize_run(
        self,
        analysis_run_id: str,
        workflow: NarrativeAnalystWorkflow,
        real_llm_requested: bool,
    ) -> NarrativeAnalysisRunV1:
        run = self._analysis_repository.get_run(analysis_run_id)
        if run is None:
            raise ValueError("NarrativeAnalysisRun not found")
        windows = self._analysis_repository.list_windows(analysis_run_id)
        failed_count = sum(
            window.status == NarrativeAnalysisWindowStatus.FAILED for window in windows
        )
        succeeded_count = sum(
            window.status == NarrativeAnalysisWindowStatus.SUCCEEDED for window in windows
        )
        status = (
            NarrativeAnalysisRunStatus.SUCCEEDED
            if failed_count == 0
            else NarrativeAnalysisRunStatus.PARTIAL_FAILED
            if succeeded_count > 0
            else NarrativeAnalysisRunStatus.FAILED
        )
        completed = run.model_copy(update={"status": status, "updated_at": datetime.now(UTC)})
        saved = self._analysis_repository.save_run(completed)
        self._save_aggregate_result(saved, windows)
        if saved.status == NarrativeAnalysisRunStatus.SUCCEEDED:
            reviewed = NarrativeAnalysisReviewCoordinator(
                source_repository=self._source_repository,
                analysis_repository=self._analysis_repository,
            ).review_if_ready(saved.analysis_run_id)
            if self._recovery_repository is not None:
                def rerun(directive, attempt_id):  # type: ignore[no-untyped-def]
                    result = workflow.run(
                        project_id=directive.project_id,
                        mode=directive.mode,
                        chunk_ids=directive.ordered_source_chunk_ids,
                        chunk_limit=len(directive.ordered_source_chunk_ids),
                        max_chars_per_chunk=directive.max_chars_per_chunk,
                        execution_nonce=attempt_id,
                        real_llm_requested=real_llm_requested,
                    )
                    return result.agent_run

                get_agent_run = getattr(self._agent_run_repository, "get_agent_run", None)
                if callable(get_agent_run):
                    NarrativeAnalysisRecoveryCoordinator(
                        source_repository=self._source_repository,
                        analysis_repository=self._analysis_repository,
                        recovery_repository=self._recovery_repository,
                        policy=default_recovery_policy(),
                        rerun_window=rerun,
                        get_agent_run=get_agent_run,
                    ).recover_if_eligible(
                        reviewed.analysis_run_id, real_llm_requested=real_llm_requested
                    )
            return reviewed
        return saved

    def _save_aggregate_result(
        self,
        run: NarrativeAnalysisRunV1,
        windows: list[NarrativeAnalysisWindowV1],
    ) -> None:
        get_agent_run = getattr(self._agent_run_repository, "get_agent_run", None)
        if not callable(get_agent_run):
            return
        sources: list[NarrativeAnalysisProposalSourceV1] = []
        for window in windows:
            if window.status != NarrativeAnalysisWindowStatus.SUCCEEDED or not window.agent_run_id:
                continue
            agent_run = get_agent_run(window.agent_run_id)
            if not hasattr(agent_run, "payload"):
                continue
            sources.extend(proposal_sources_for_window(agent_run, window))
        typed_sources = sources
        self._analysis_repository.save_result(
            aggregate_narrative_analysis(typed_sources, analysis_run_id=run.analysis_run_id)
        )
