"""Export core Pydantic schemas to JSON Schema files."""

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from pydantic import BaseModel, TypeAdapter

from comic_agent.schemas import (
    AgentInputRefV1,
    AgentOutputRefV1,
    AgentRunV1,
    AggregatedRelationshipSignalProposalV1,
    AggregatedStateChangeProposalV1,
    ApprovedProposalBundleV1,
    ApprovedSourceChunkBundleV1,
    CampusContentProfileProposalV1,
    CharacterStateV1,
    ClaimProposalBatchV1,
    ClaimProposalV1,
    ComicBeatProposalV1,
    CommitPlanV1,
    ConflictV1,
    EntityProposalBatchV1,
    EntityProposalV1,
    EventProposalBatchV1,
    EventProposalV1,
    EvidenceRefV1,
    KnowledgeStateEvaluationCaseBatchV1,
    KnowledgeStateEvaluationCaseSummaryV1,
    KnowledgeStateEvaluationCaseV1,
    KnowledgeStateEvaluationEvaluateRequestV1,
    KnowledgeStateEvaluationFailureDiagnosticsV1,
    KnowledgeStateEvaluationPolicyV1,
    KnowledgeStateEvaluationReportRequestV1,
    KnowledgeStateEvaluationReportV1,
    KnowledgeStateEvaluationResultV1,
    KnowledgeStateEvaluationRunFailureV1,
    KnowledgeStateEvaluationRunRequestV1,
    KnowledgeStateEvaluationRunResultV1,
    KnowledgeStateExpectationV1,
    KnowledgeStateProposalBatchV1,
    KnowledgeStateProposalV1,
    KnowledgeStateStateMatcherV1,
    KnowledgeSubjectRefV1,
    KnowledgeTargetRefV1,
    KnowledgeTemporalAnchorV1,
    MockProviderResultV1,
    NarrativeAnalysisProposalSourceV1,
    NarrativeAnalysisResultV1,
    NarrativeAnalysisReviewRouteV1,
    NarrativeAnalysisWindowPlanV1,
    NarrativeAnalysisWindowV1,
    PanelSpecV1,
    ProfileUpdateProposalV1,
    ProjectSpecV1,
    ProposalRecoveryDiagnosticV1,
    ProposalReviewDecisionV1,
    ProviderResultV1,
    QAResultV1,
    RecoveryAttemptV1,
    RecoveryBudgetUsageV1,
    RecoveryDirectiveV1,
    RecoveryOutcomeV1,
    RecoveryPolicyV1,
    ReferenceResolutionDecisionV1,
    RelationshipContextEventRefV1,
    RelationshipParticipantRefV1,
    RelationshipSignalProposalBatchV1,
    RelationshipSignalProposalV1,
    RelationshipSourceSpeakerRefV1,
    RelationshipTemporalAnchorV1,
    RelationshipUpdateProposalV1,
    RepairPlanV1,
    ReviewableProposalEnvelopeV1,
    ReviewGate1CategoryCountV1,
    ReviewGate1CheckResultV1,
    ReviewGate1InputV1,
    ReviewGate1IssueCountV1,
    ReviewGate1IssueV1,
    ReviewGate1MetricsV1,
    ReviewGate1PolicyV1,
    ReviewGate1ResultV1,
    ReviewGate1RoutingAdviceV1,
    ReviewGate2InputV1,
    ReviewGate2PolicyV1,
    ReviewGate2ResultV1,
    ReviewIssueV1,
    SceneSpecV1,
    SourceChapterReviewItemV1,
    SourceChapterV1,
    SourceChunkReviewItemV1,
    SourceChunkV1,
    SourceDocumentV1,
    SourceTextAuditSnapshotV1,
    StateChangeEventRefV1,
    StateChangeProposalBatchV1,
    StateChangeProposalV1,
    StateChangeTargetRefV1,
    StateUpdateProposalV1,
    StoryBeatV1,
    StoryBibleContextV1,
    StoryBibleCuratorProposalV1,
    StoryBibleUpdateV1,
    StoryEntityProfileV1,
    StoryEntityStateV1,
    StoryRelationshipV1,
    TemporalRelationProposalV1,
    TimelineAnalysisInputV1,
    TimelineAnalysisProposalV1,
    TimelineConflictV1,
    WorkflowRunV1,
    WorldRuleUpdateProposalV1,
    WorldRuleV1,
)

SCHEMAS: list[type[BaseModel]] = [
    AgentRunV1,
    EvidenceRefV1,
    ProjectSpecV1,
    SourceDocumentV1,
    SourceChapterV1,
    SourceChunkV1,
    EntityProposalV1,
    EntityProposalBatchV1,
    EventProposalV1,
    EventProposalBatchV1,
    ClaimProposalV1,
    ClaimProposalBatchV1,
    CampusContentProfileProposalV1,
    ComicBeatProposalV1,
    KnowledgeStateProposalV1,
    KnowledgeStateProposalBatchV1,
    KnowledgeStateEvaluationCaseV1,
    KnowledgeStateEvaluationCaseSummaryV1,
    KnowledgeStateEvaluationCaseBatchV1,
    KnowledgeStateExpectationV1,
    KnowledgeStateStateMatcherV1,
    KnowledgeStateEvaluationPolicyV1,
    KnowledgeStateEvaluationReportRequestV1,
    KnowledgeStateEvaluationReportV1,
    KnowledgeStateEvaluationFailureDiagnosticsV1,
    KnowledgeStateEvaluationResultV1,
    KnowledgeStateEvaluationEvaluateRequestV1,
    KnowledgeStateEvaluationRunRequestV1,
    KnowledgeStateEvaluationRunFailureV1,
    KnowledgeStateEvaluationRunResultV1,
    KnowledgeSubjectRefV1,
    KnowledgeTargetRefV1,
    KnowledgeTemporalAnchorV1,
    TemporalRelationProposalV1,
    TimelineAnalysisInputV1,
    TimelineAnalysisProposalV1,
    TimelineConflictV1,
    StateChangeEventRefV1,
    StateChangeTargetRefV1,
    StateChangeProposalV1,
    StateChangeProposalBatchV1,
    RelationshipParticipantRefV1,
    RelationshipSourceSpeakerRefV1,
    RelationshipTemporalAnchorV1,
    RelationshipContextEventRefV1,
    RelationshipSignalProposalV1,
    RelationshipSignalProposalBatchV1,
    NarrativeAnalysisProposalSourceV1,
    AggregatedRelationshipSignalProposalV1,
    AggregatedStateChangeProposalV1,
    NarrativeAnalysisResultV1,
    NarrativeAnalysisWindowPlanV1,
    NarrativeAnalysisWindowV1,
    WorkflowRunV1,
    AgentInputRefV1,
    AgentOutputRefV1,
    ProviderResultV1,
    MockProviderResultV1,
    AgentRunV1,
    CharacterStateV1,
    SceneSpecV1,
    StoryBeatV1,
    PanelSpecV1,
    QAResultV1,
    RepairPlanV1,
    StoryBibleContextV1,
    StoryEntityProfileV1,
    StoryEntityStateV1,
    StoryRelationshipV1,
    WorldRuleV1,
    ProfileUpdateProposalV1,
    StateUpdateProposalV1,
    RelationshipUpdateProposalV1,
    WorldRuleUpdateProposalV1,
    ConflictV1,
    CommitPlanV1,
    StoryBibleCuratorProposalV1,
    ReviewIssueV1,
    ReferenceResolutionDecisionV1,
    ReviewableProposalEnvelopeV1,
    ReviewGate2PolicyV1,
    ReviewGate2InputV1,
    ProposalReviewDecisionV1,
    ApprovedProposalBundleV1,
    ApprovedSourceChunkBundleV1,
    ReviewGate2ResultV1,
    NarrativeAnalysisReviewRouteV1,
    ProposalRecoveryDiagnosticV1,
    RecoveryPolicyV1,
    RecoveryBudgetUsageV1,
    RecoveryDirectiveV1,
    RecoveryOutcomeV1,
    RecoveryAttemptV1,
    ReviewGate1CheckResultV1,
    ReviewGate1InputV1,
    ReviewGate1IssueV1,
    ReviewGate1PolicyV1,
    ReviewGate1ResultV1,
    ReviewGate1IssueCountV1,
    ReviewGate1CategoryCountV1,
    ReviewGate1MetricsV1,
    ReviewGate1RoutingAdviceV1,
    SourceChapterReviewItemV1,
    SourceChunkReviewItemV1,
    SourceTextAuditSnapshotV1,
]


def main() -> None:
    """Write JSON Schema files."""

    output_dir = Path("schema_exports")
    output_dir.mkdir(exist_ok=True)
    for model in SCHEMAS:
        path = output_dir / f"{model.__name__}.json"
        path.write_text(
            json.dumps(model.model_json_schema(), ensure_ascii=False, indent=2),
            encoding="utf-8",
        )
    update_path = output_dir / "StoryBibleUpdateV1.json"
    update_path.write_text(
        json.dumps(
            TypeAdapter(StoryBibleUpdateV1).json_schema(),
            ensure_ascii=False,
            indent=2,
        ),
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
